/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chitchat.forms;

import chitchat.component.ItemPeople;
import chitchat.event.EventLeftMenu;
import chitchat.event.PublicEvent;
import chitchat.models.UserAccountModel;
import chitchat.swing.utilities.ScrollBar;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Jatin Wadhwani
 */
public class LeftMenu extends javax.swing.JPanel {

    /**
     * Creates new form Menu_Left
     */
    private List<UserAccountModel> userAccounts;
    public LeftMenu() {
        initComponents();
        init();
    }

    private void init() {
        scrollBar.setVerticalScrollBar(new ScrollBar());
        menuList.setLayout(new MigLayout("fillx" , "0[]0" , "0[]0"));
        userAccounts = new ArrayList<>();
        PublicEvent.getInstance().addEventLeftMenu(new EventLeftMenu(){
            @Override
            public void newUser(List<UserAccountModel> users) {
                for (UserAccountModel user : users) {
                    userAccounts.add(user);
                    menuList.add(new ItemPeople(user), "wrap");
//                    System.out.println(getClass() + "Inside newUser() Line 42: status = " + user.isStatus());
//                    System.out.println(getClass() + "Inside newUser() Line 44: age = " + user.getAge());
                    refreshMenuList();
                }
            }
            
            @Override
            public void connectUser(int userId) {
                for(UserAccountModel user : userAccounts) {
                    if(user.getUserId() == userId) {
                        user.setStatus(true);
                        PublicEvent.getInstance().getEventMain().updateUser(user);
                        break;
                    }
                }
                if(menuMessage.isSelected()) {
                    for(Component component: menuList.getComponents()) {
                        ItemPeople item = (ItemPeople)component;
                        if(item.getUser().getUserId() == userId) {
                            item.updateStatus();
                            break;
                        }
                    }
                }
            }
            @Override
            public void disconnectUser(int userId) {
                for(UserAccountModel user : userAccounts) {
                    if(user.getUserId() == userId) {
                        user.setStatus(false);
                        PublicEvent.getInstance().getEventMain().updateUser(user);
                        break;
                    }
                }
                if(menuMessage.isSelected()) {
                    for(Component component: menuList.getComponents()) {
                        ItemPeople item = (ItemPeople)component;
                        if(item.getUser().getUserId() == userId) {
                            item.updateStatus();
                            break;
                        }
                    }
                }
            }
        });
        showMessage();
    }
    
    private void showMessage() {
//        Testing data
        menuList.removeAll();
        for(UserAccountModel user : userAccounts) {
            menuList.add(new ItemPeople(null), "wrap");
        }
        refreshMenuList();
    }
    
    private void showGroup() {
//        Testing data
        menuList.removeAll();
        for(int i = 0 ; i < 7 ; i++) {
            menuList.add(new ItemPeople(null) , "wrap");
        }
        refreshMenuList();
    }
    private void showBox() {
//        Testing data
        menuList.removeAll();
        for(int i = 0 ; i < 5 ; i++) {
            menuList.add(new ItemPeople(null) , "wrap");
        }
        refreshMenuList();
    }
    
    private void refreshMenuList() {
        menuList.repaint();
        menuList.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JLayeredPane();
        menuMessage = new chitchat.component.MenuButton();
        menuGroup = new chitchat.component.MenuButton();
        menuBox = new chitchat.component.MenuButton();
        scrollBar = new javax.swing.JScrollPane();
        menuList = new javax.swing.JLayeredPane();

        setBackground(new java.awt.Color(229, 229, 229));

        menu.setBackground(new java.awt.Color(229, 229, 229));
        menu.setOpaque(true);
        menu.setPreferredSize(new java.awt.Dimension(150, 40));
        menu.setLayout(new java.awt.GridLayout(1, 3));

        menuMessage.setIconSelected(new javax.swing.ImageIcon(getClass().getResource("/chitchat/icons/message_selected.png"))); // NOI18N
        menuMessage.setSelected(true);
        menuMessage.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/chitchat/icons/message.png"))); // NOI18N
        menuMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMessageActionPerformed(evt);
            }
        });
        menu.add(menuMessage);

        menuGroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chitchat/icons/group.png"))); // NOI18N
        menuGroup.setIconSelected(new javax.swing.ImageIcon(getClass().getResource("/chitchat/icons/group_selected.png"))); // NOI18N
        menuGroup.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/chitchat/icons/group.png"))); // NOI18N
        menuGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGroupActionPerformed(evt);
            }
        });
        menu.add(menuGroup);

        menuBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chitchat/icons/box.png"))); // NOI18N
        menuBox.setIconSelected(new javax.swing.ImageIcon(getClass().getResource("/chitchat/icons/box_selected.png"))); // NOI18N
        menuBox.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/chitchat/icons/box.png"))); // NOI18N
        menuBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBoxActionPerformed(evt);
            }
        });
        menu.add(menuBox);

        scrollBar.setBackground(new java.awt.Color(229, 229, 229));
        scrollBar.setBorder(null);
        scrollBar.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        menuList.setBackground(new java.awt.Color(229, 229, 229));
        menuList.setOpaque(true);
        menuList.setPreferredSize(new java.awt.Dimension(0, 576));

        javax.swing.GroupLayout menuListLayout = new javax.swing.GroupLayout(menuList);
        menuList.setLayout(menuListLayout);
        menuListLayout.setHorizontalGroup(
            menuListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        menuListLayout.setVerticalGroup(
            menuListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );

        scrollBar.setViewportView(menuList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, Short.MAX_VALUE)
            .addComponent(scrollBar)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(scrollBar, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void menuMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMessageActionPerformed
        if(!menuMessage.isSelected()){
            menuMessage.setSelected(true);
//            menuGroup.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/chitchat/icons/group.png")));
//            menuBox.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/chitchat/icons/box.png")));
            menuGroup.setSelected(false);
            menuBox.setSelected(false);
            showMessage();
        }
    }//GEN-LAST:event_menuMessageActionPerformed

    private void menuGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGroupActionPerformed
        if(!menuGroup.isSelected()) {
            menuMessage.setSelected(false);
            menuGroup.setSelected(true);
//            menuMessage.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/chitchat/icons/message.png")));
//            menuBox.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/chitchat/icons/box.png")));
            menuBox.setSelected(false);
            showGroup();
        }    
    }//GEN-LAST:event_menuGroupActionPerformed

    private void menuBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBoxActionPerformed
        if(!menuBox.isSelected()) {
            menuMessage.setSelected(false);
            menuGroup.setSelected(false);
            menuBox.setSelected(true);
//            menuGroup.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/chitchat/icons/group.png")));
//            menuMessage.setSimpleIcon(new javax.swing.ImageIcon(getClass().getResource("/chitchat/icons/message.png")));
            showBox();
        }
    }//GEN-LAST:event_menuBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane menu;
    private chitchat.component.MenuButton menuBox;
    private chitchat.component.MenuButton menuGroup;
    private javax.swing.JLayeredPane menuList;
    private chitchat.component.MenuButton menuMessage;
    private javax.swing.JScrollPane scrollBar;
    // End of variables declaration//GEN-END:variables
}
