/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chitchat.forms;

import chitchat.event.EventMessage;
import chitchat.event.PublicEvent;
import chitchat.models.MessageModel;
import chitchat.models.RegisterModel;
import utility.PasswordEncryption;

/**
 *
 * @author Jatin Wadhwani
 */
public class RegisterFrame extends javax.swing.JPanel {

    /**
     * Creates new form PLogin
     */
    private String userName, password, confirmPassword;
    private int age;

    public RegisterFrame() {
//        System.out.println(RegisterFrame.class + " Line 21(Inside Constructor)");
        initComponents();
        txtUserName.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        btnGoLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblError = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("SansSerif", 0, 30)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(86, 86, 86));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Register");

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel1.setText("User Name");

        txtUserName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel2.setText("Password");

        txtPassword.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        btnRegister.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnGoLogin.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        btnGoLogin.setForeground(new java.awt.Color(16, 130, 206));
        btnGoLogin.setText("Login");
        btnGoLogin.setContentAreaFilled(false);
        btnGoLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoLoginActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel3.setText("Confirm Password");

        txtConfirmPassword.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel4.setText("Enter your age");

        txtAge.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        lblError.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAge)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtConfirmPassword))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoLoginActionPerformed
        clear();
        PublicEvent.getInstance().getEventLogin().goLogin();
    }//GEN-LAST:event_btnGoLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        if (validInputs()) {
//            System.out.println(getClass() + " Line 167: actionPerformed()");
            RegisterModel data = new RegisterModel(userName, password, age);
            PublicEvent.getInstance().getEventLogin().register(data, new EventMessage() {
                @Override
                public void callMessage(MessageModel message) {
//                    System.out.println(getClass() + " Line 172: callMessage()");
                    if (!message.isAction()) {
//                        System.out.println(getClass() + " Line 174: isAction = " + message.isAction());
                        lblError.setText(message.getMessage());
                    } else {
//                        RegisterModel data = new RegisterModel(userName, password, age);
//                        System.out.println(getClass() + " Line 178 data = " + data);
//                        PublicEvent.getInstance().getEventLogin().register(data, new EventMessage() {
//                            @Override
//                            public void callMessage(MessageModel message) {
//                                System.out.println(getClass() + " Line 182 action = " + message.isAction());
//                                if (!message.isAction()) {
//                                    lblError.setText(message.getMessage());
//                                } else {
                                    PublicEvent.getInstance().getEventMain().initChat();
//                                }
//                            }
//                        });
//                        System.out.println(getClass() + " Line 190");
                    }
                }
            });
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private boolean validInputs() {
        userName = txtUserName.getText().trim();
        if (userName.equals("")) {
            txtUserName.requestFocusInWindow();
            return false;
        }

        char[] pwd = txtPassword.getPassword();
        char[] confirmPwd = txtConfirmPassword.getPassword();
        if (pwd.length == 0) {
            txtPassword.requestFocusInWindow();
            return false;
        }
        if (confirmPwd.length == 0) {
            txtConfirmPassword.requestFocusInWindow();
            return false;
        }
        password = new String(pwd);
        confirmPassword = new String(confirmPwd);
        if (!password.equals(confirmPassword)) {
            txtPassword.requestFocusInWindow();
            return false;
        }

        for (int i = 0; i < password.length(); i++) {
            pwd[i] = 'i';
        }
        for (int i = 0; i < confirmPassword.length(); i++) {
            confirmPwd[i] = 'i';
        }
        pwd = null;
        confirmPwd = null;
        System.gc();
        System.runFinalization();

        password = PasswordEncryption.getEncryptedPassword(password);
        confirmPassword = PasswordEncryption.getEncryptedPassword(confirmPassword);
        
        if (!isAgeValid()) {
            txtAge.requestFocusInWindow();
            return false;
        }

        return true;
    }

    private boolean isAgeValid() {
        try {
            age = Integer.parseInt(txtAge.getText().trim());
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAge;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        txtUserName.setText("");
        txtPassword.setText("");
        txtConfirmPassword.setText("");
    }
}
