/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chitchat.component;

import java.awt.Color;
import javax.swing.Icon;

/**
 *
 * @author Jatin Wadhwani
 */
public class ChatLeftPart extends javax.swing.JLayeredPane {

    /**
     * Creates new form ChatLeftPart
     */
    public ChatLeftPart() {
        initComponents();
        chatItem.setBackground(new Color(229,229,229));
    }

    public void setImage(Icon... image) {
        chatItem.setImage(false, image);
    }
    
    public void setImage(String... image) {
        chatItem.setImage(false, image);
    }
    
    public void setFile(String fileName , String fileSize) {
        chatItem.setFile(fileName, fileSize);
    }
    
    public void setEmoji(Icon icon) {
        chatItem.hideText();
        chatItem.setEmoji(false, icon);
    }
    
    public void setTime() {
        chatItem.setTime("10:36 PM"); //Testing Data
    }
    
    public void setText(String text) {
        if(text.equals("")) {
            chatItem.hideText();
        }
        else {
            chatItem.setText(text);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chatItem = new chitchat.component.ChatItem();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private chitchat.component.ChatItem chatItem;
    // End of variables declaration//GEN-END:variables
}
