/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chitchat.component;

import java.awt.Color;
import javax.swing.Icon;

/**
 *
 * @author Jatin Wadhwani
 */
public class ChatLeftPartWithProfile extends javax.swing.JLayeredPane {

    /**
     * Creates new form ChatLeftPart
     */
    public ChatLeftPartWithProfile() {
        initComponents();
        chatItem.setBackground(new Color(229,229,229));
    }

    public void setUserProfile(String userProfile) {
        chatItem.setUserProfile(userProfile);
    }
    public void setProfilePicture(Icon profilePicture) {
        iaImage.setImage(profilePicture);
    }
    
    public void setImage(Icon... image) {
        chatItem.setImage(false, image);
    }
    
    public void setImage(String... image) {
        chatItem.setImage(false, image);
    }
    
    public void setFile(String fileName , String fileSize) {
        chatItem.setFile(fileName, fileSize);
    }
    
    public void setTime() {
        chatItem.setTime("10:36 PM"); //Testing Data
    }
    
    public void setText(String text) {
        if(text.equals("")) {
            chatItem.hideText();
        }
        else {
            chatItem.setText(text);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        iaImage = new chitchat.swing.utilities.ImageAvatar();
        chatItem = new chitchat.component.ChatItem();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(31, 31));

        iaImage.setBorderSize(0);
        iaImage.setImage(new javax.swing.ImageIcon(getClass().getResource("/chitchat/icons/profile.png"))); // NOI18N
        iaImage.setMaximumSize(new java.awt.Dimension(31, 31));
        iaImage.setMinimumSize(new java.awt.Dimension(31, 31));
        iaImage.setPreferredSize(new java.awt.Dimension(31, 31));

        jLayeredPane1.setLayer(iaImage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(iaImage, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iaImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        add(jLayeredPane1);
        add(chatItem);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private chitchat.component.ChatItem chatItem;
    private chitchat.swing.utilities.ImageAvatar iaImage;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
