/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chitchat.component;

import chitchat.event.PublicEvent;
import chitchat.swing.utilities.PictureBox;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Icon;
import javax.swing.SwingUtilities;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Jatin Wadhwani
 */
public class ChatImage extends javax.swing.JLayeredPane {

    /**
     * Creates new form ChatImage
     */
    public ChatImage() {
        initComponents();
        setLayout(new MigLayout("" , "0[]0" , "3[]3"));
    }

    public ChatImage(boolean right) {
        this();
        setLayout(new MigLayout("" , "0["+(right?"right":"left")+"]0" , "3[]3"));
    }
    
    public void addImage(Icon... image) {
        for(Icon images :image) {
            PictureBox pic = new PictureBox();
            pic.setPreferredSize(getAutoSize(images , 200 , 200));
            pic.setImage(images);
            addEvent(pic , images);
            add(pic , "wrap");
        }
    }
    
    public void addImage(String... image) {
        for(String images :image) {
            ImageItem pic = new ImageItem();
            pic.setPreferredSize(new Dimension(200,200)); // for testing purpose
            pic.setImage(images);
            //addEvent(pic , images);
            add(pic , "wrap");
        }
    }
    
    private void addEvent(Component component , Icon image) {
        component.setCursor(new Cursor(Cursor.HAND_CURSOR));
        component.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                if(SwingUtilities.isLeftMouseButton(evt)) {
                    PublicEvent.getInstance().getEventImageView().viewImage(image);
                }
            }
        });
    }
    
    private Dimension getAutoSize(Icon image , int w , int h) {
        if (w > image.getIconWidth()) {
            w = image.getIconWidth();
        }
        if (h > image.getIconHeight()) {
            h = image.getIconHeight();
        }
        int iw = image.getIconWidth();
        int ih = image.getIconHeight();
        double xScale = (double) w / iw;
        double yScale = (double) h / ih;
        double scale = Math.min(xScale, yScale);
        int width = (int) (scale * iw);
        int height = (int) (scale * ih);
        return new Dimension(width, height);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
